version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
  build:
    commands:
      - echo Building the frontend Docker image...
      - docker build -t frontend-image .
      - docker tag frontend-image:latest $ECR_REPOSITORY_URL:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URL:latest
      - echo Frontend build complete!
