version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URL .
      - echo Tagging the image...
      - docker tag $ECR_REPOSITORY_URL:latest $ECR_REPOSITORY_URL:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URL:latest
